[package]
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
edition = "2018"
name = "rust-bitcoin-indexer"
version = "0.1.0"

[[bench]]
harness = false
name = "bitcoincore_rpc"

[dependencies]
bitcoin = "0.15"
bitcoin-bech32 = "*"
bitcoincore-rpc = "0.1"
common_failures = "*"
failure = "*"
hex = "*"
secp256k1 = "*"
crossbeam-channel = "*"
structopt = "*"
default = "*"
dotenv = "*"
postgres = "*"
insideout = "*"
num_cpus = "1"
log = "0.4"
rayon = "1"

# r2d2 = "*"

[dev-dependencies]
criterion = "0.2"
