[package]
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
edition = "2018"
name = "rust-bitcoin-indexer"
version = "0.1.0"

[[bench]]
harness = false
name = "bitcoincore_rpc"

[dependencies]
bitcoin = "*"
common_failures = "*"
hex = "*"
crossbeam-channel = "*"
structopt = "*"
default = "*"
diesel = { version = "1", features = ["postgres", "chrono"] }
#diesel_infer_schema = { version = "1", features = ["postgres"] }
#diesel_codegen = { version = "*", features = ["postgres"] }
r2d2 = "*"
r2d2-diesel = "*"

[dependencies.bitcoin-rpc]
path = "../rust-bitcoin-rpc"
#git = "https://github.com/dpc/rust-bitcoin-rpc/"
#branch = "dpc-dev"

[dev-dependencies]
criterion = "0.2"
